### ISSUE TITLE
Link to Docksal setup is incorrect

### ISSUE THREAD

**Issue by BrizzleRocker** [docksal/boilerplate-drupal8#35]
Goes to a dead page - `https://docs.docksal.io/en/master/getting-started/env-setup`

Correct link is: `https://docs.docksal.io/getting-started/setup/`

**Comment by BrizzleRocker** [comment]
Here's a patch seeing as I can't commit a new branch :D 
[update-README.patch.txt](https://github.com/docksal/boilerplate-drupal8/files/3074162/update-README.patch.txt)

**Comment by shelane** [comment]
Thanks! I've updated the link as well as another on fin custom commands.
