### ISSUE TITLE
Admin username and password

### ISSUE THREAD

**Issue by philchanet** [docksal/boilerplate-drupal8#45]
Please pardon my ignorance...
I've successfully installed the Docksal Drupal 8 boilerplate on my Mac and things went smoothly. I'm now stuck on the Login page: could you please help me find the default admin username and password?
Thanks : )

**Comment by philchanet** [comment]
I've browsed through my install log and managed to find the username and password - sorry for bothering you.

**Comment by achekulaev** [comment]
@philchanet usually you either use those from the log, as you have found, or you get the reset password link using `fin drush uli` command, and log in with it.
